### ISSUE TITLE
Consider `to` in addition to `andThen`

### ISSUE THREAD

**Issue by kitlangton** [optics-dev/Monocle#1014]
I just wrote a [reddit comment](https://www.reddit.com/r/scala/comments/l1ugt5/monocle_3_roadmap/gkg7p2e/?utm_source=reddit&utm_medium=web2x&context=3) on this, but perhaps a GitHub issue would be a home for it 😄 . To paraphrase:

Monocle 3 is an extremely exciting direction for the library to take. I love everything about it.

One tiny suggestion, though it's syntactic and I'm quite cool either way, would be to consider using `to` instead of (or in addition to) `andThen`. The `composeVariants` spread out and visually dominated the meaningful bits of the composition, those being the actual optics themselves. As composition is the primary operator, it could be nice to make it as syntactically diminutive as possible.

For comparison: 

`Group.users composeTraversal accounts composeTraversal orders composeOptional id`
`Group.users andThen accounts andThen orders andThen id`
`Group.users to accounts to orders to id`

The last one, to me, is easiest to trace the important path of `users -> accounts -> orders -> id`.

Thanks for all of your hard work, Julien (and everyone!)!

_P.S. If this **is** something you'd be into, I'd happily volunteer to open a PR for it._

**Comment by kitlangton** [comment]
Resolved here: https://reddit.com/r/scala/comments/l1ugt5/_/gkxgxu9/ 👍😎

**Comment by julien-truffaut** [comment]
Sorry @kitlangton, I swore I saw a comment from you but I couldn't remember where it was. I didn't check Monocle issues :(
