### ISSUE TITLE
Release for Scala 3.0.0 M3

### ISSUE THREAD

**Issue by romainreuillon** [optics-dev/Monocle#1061]
Dear Monocle Devs,

from what I have read in the doc monocle is released for scala 3.0.0 M3. However, I cannot find monocle dependency for scala 3.0.0-M3 in maven central: https://repo1.maven.org/maven2/com/github/julien-truffaut/

Is it a the place right place to look for it?

Best regards,
Romain

**Comment by julien-truffaut** [comment]
Hi Romain, sorry for the confusion. I updated the website too early, there is no version release for Scala 3.0.0-M3 yet.

The latest version currently available is https://github.com/optics-dev/Monocle/releases/tag/v2.1.0

We intend to release the first milestone of Monocle 3.0.0 by Wednesday this week. It will be available for Scala 3.0.0-M3 and Scala 2.13.

**Comment by romainreuillon** [comment]
Dear Julien,

thanks for your answer. I'm eager to try this new version !

FYI just a bit of context: we implement large simulation model (million of agents and million of cells) and Monocle is a very elegant way to compress the model data while keeping the code logic readable. An example of that can be found here: https://github.com/eighties-cities/h24/blob/master/src/main/scala/eighties/h24/social.scala. In this model we animate 8 millions human agents with sociological attributes and we make it fit in less than 2GB of RAM. The model I am starting now is about dengue epidemic at the scale of an entire city.

Romain

**Comment by julien-truffaut** [comment]
That sounds awesome. I will update this ticket as soon as the new version is released.

FYI, I am going to present Monocle 3 on Thursday: https://www.meetup.com/Scala-Berlin-Brandenburg/events/275841617/

**Comment by romainreuillon** [comment]
Great ! Thank for the link.

**Comment by julien-truffaut** [comment]
@romainreuillon It is available. Here is the release note:

https://github.com/optics-dev/Monocle/releases/tag/v3.0.0-M1

**Comment by romainreuillon** [comment]
:+1: :champagne:
