### ISSUE TITLE
Question: Would you consider implementing some cats instances for optics?

### ISSUE THREAD

**Issue by vaslabs** [optics-dev/Monocle#1087]
Hello,
I understand that my use case maybe a bit peculiar but anyway, long story short I needed to do something like 
[this](https://github.com/vaslabs/Monocle/commit/5216d912ce415a81f230ff701b08c6339738f5c4#diff-007ad103a52ea4afe202ac763485c26b2e5a3bf397696e5af026676455d08ff3R73)

Which needed `Invariant[Lens]` and `Semigroupal[Lens]` (or InvariantSemigroupal but I kept them separate in this linked snippet)

Would you like this kind of thing (i.e. implementing some cats instances in monocle) here? Could be a separate module dedicated for cats (I've seen there's State in a separate module), although that could mean a separate import to make `cats.syntax._` work

Let me know your thoughts, I could contribute the ones in the snippet (and possibly more?).

Edit:
I've also haven't looked into doing this for the full `PLens[S, T, A, B]`

**Comment by julien-truffaut** [comment]
Hey @vaslabs and thanks for the question.

We were planning to add similar functionalities https://github.com/optics-dev/Monocle/issues/1019

The benfit of using cats `Semigroupal` is that we get all the syntax out of the box but we need an extra import for cats syntax. I don't have a strong opinion about it.

We already have cats instances within the `core` module, e.g. `Choice[Lens]`

**Comment by vaslabs** [comment]
Thanks for the response.

I've just read #1019 , this is a bit different than zip (I think) as it gives all the syntax from cats (including mapN, map2 and anything derived from semigroupal and invariant)

But what you mention is a bit worrying:

> One thing to note is that tupled can break the optics which is fine, it only happens if the Lenses intersect.

Please excuse my ignorance here , but what does it mean for Lenses to intersect? Could you give some pointers to see if I manage to replicate this breaking with a test?

**Comment by julien-truffaut** [comment]
Sorry I didn't give you enough context, I recently made a presentation where I show the potential issue with `zip` , slide 72 to 79: https://blog.fp-tower.com/monocle-3-a-peek-into-the-future/#72

IMO, `tupled` is completely fine, but I don't think `mapN` is possible, here is a counter example:
```scala
case class Point(x: Int, y: Int)

val sum: Lens[Point, Int] = (Focus[Point](_.x), Focus[Point](_.y)).map2(_ + _)

sum.get(Point(3, 5)) // that's fine
// res = 8

sum.replace(10)(Point(3, 5)) // how would you split 10 into x and y?
```

What we would need is `mapN` to take an `Iso` not a single function.

I think that's completely fine to add `Invariant` and `Semigroupal` instances. We can always add something custom in Monocle later if we want to.

**Comment by vaslabs** [comment]
thanks for the pointers, I'll read up and send a PR (probably next week)

**Comment by vaslabs** [comment]
>IMO, tupled is completely fine, but I don't think mapN is possible, here is a counter example:

Ah yeah, actually it's imapN that works because it's easy to have an Invariant but probably you can't prove Lens is a Functor. Probably easy though for `Getter`
