### ISSUE TITLE
Update the organisation to optics.dev

### ISSUE THREAD

**Issue by julien-truffaut** [optics-dev/Monocle#1161]
A few people asked me if we are going to update the organisation name. Monocle 3 is definitely the best time to do it.

I haven't created a sonatype account for ages, I am not sure what the process is. If anyone has links or would like to pick up the task, that would be awesome!

**Comment by julien-truffaut** [comment]
I created a ticket to sonatype https://issues.sonatype.org/browse/OSSRH-69548

**Comment by armanbilge** [comment]
If you created a new Sonatype account, it might be using [their new domain](https://central.sonatype.org/news/20210223_new-users-on-s01/) s01.oss.sonatype.org. So you need to specify this in the `build.sbt`:

```
sonatypeCredentialHost := "s01.oss.sonatype.org"
sonatypeRepository := "https://s01.oss.sonatype.org/service/local"
```

**Comment by julien-truffaut** [comment]
@armanbilge Cheers, I tried that but it seems that it doesn't update the publication. Maybe I need to put those settings somewhere else?
https://github.com/optics-dev/Monocle/blob/master/build.sbt#L14-L15

**Comment by julien-truffaut** [comment]
Fixed thanks
