### ISSUE TITLE
Cannot generate lens for case classes inheriting traits

### ISSUE THREAD

**Issue by JonyEpsilon** [optics-dev/Monocle#1188]
I had expected the following would be possible:

```scala
package jstar.scratch

import monocle.macros.GenLens

trait Animal {
  def name: String
}

case class Elephant(name: String) extends Animal
case class Otter(name: String, age: Integer) extends Animal
case class Menagerie(animals: List[Animal])

@main def main(): Unit = {
  val f = Menagerie(List(Elephant("Steve")))
  println(f)
  val l = GenLens[Menagerie](_.animals.index(0).name)
  val g = l.replace("Bob")(f)
  println(g)
  println(f)
}
```

but it fails with message `Cannot generate Lens for field 'name', because 'jstar.scratch.Animal' is not a case class`.

It feels like this is a reasonable way to arrange case classes, so I wonder if there's a way to support generating lenses in this situation?

**Comment by julien-truffaut** [comment]
There is a feature request for this use case https://github.com/optics-dev/Monocle/issues/1033

**Comment by JonyEpsilon** [comment]
Ahh, I didn't twig that that was the same issue from the title. Will close this one as a dupe.
