### ISSUE TITLE
TraversalLaws.headOption invalidated for underlying null values

### ISSUE THREAD

**Issue by kory33** [optics-dev/Monocle#1190]
On Monocle 3.0.0, the following code ([Scastie](https://scastie.scala-lang.org/ZaTlfW7ITema2v6kHCJkqQ)) produces `IsEq` with different `lhs` and `rhs`:

```Scala
import monocle.law.TraversalLaws
import monocle.Iso

val stringTraversal = Iso.id[String]

println(TraversalLaws(stringTraversal).headOption(null)) // IsEq(None,Some(null))
```

Simply replacing [`Option(_)`](https://github.com/optics-dev/Monocle/blob/26b276f6c29f34e693ff44f54171e5348390eed1/core/shared/src/main/scala/monocle/Fold.scala#L40-L46) with `Some(_)` should solve this.

**Comment by julien-truffaut** [comment]
Hi Kory, thanks for the ticket.

Monocle like most fp libraries don't handle null. In effect, we do as if null didn't exist in scala.

**Comment by kory33** [comment]
Hmm I see the rational, I still think using `Some(_)` is better (since, to me, `Option(_)` has a connotation of handling `null`s), but closing the issue if the law is not seen as invalidated. Thank you for the response anyway!
