### ISSUE TITLE
Bring back Native support?

### ISSUE THREAD

**Issue by kubukoz** [optics-dev/Monocle#1301]
Hi! With the recent activity around Scala Native in the Typelevel ecosystem, I was wondering if you'd consider adding back Scala Native. What do you think?

**Comment by julien-truffaut** [comment]
Hi Jakub, I am not hostile to bringing back Scala Native but I would like for someone to be responsible of its maintenance.

**Comment by armanbilge** [comment]
@julien-truffaut I'm happy to take responsibility for maintenance, if you are open to adopting [sbt-typelevel](https://typelevel.org/sbt-typelevel/) for your build. It significantly reduces the maintenance effort for OSS and cross-building.

**Comment by armanbilge** [comment]
@julien-truffaut it's currently used by more than 200 projects, including all active Typelevel and Http4s projects.

Here's a rough list:
https://github.com/typelevel/download-java/network/dependents

**Comment by julien-truffaut** [comment]
Awesome, so I am all for using it!
