### ISSUE TITLE
Autocomplete doesn't work

### ISSUE THREAD

**Issue by user753** [optics-dev/Monocle#1359]
```scala
case class Foo(foo: Int)
```
```scala
val x = Foo(100)
x.focus(_.foo).replace(200)
          ^    ^
```
I use Idea and in both places autocomplete doesn't work. But it works fine with `quicklens`
Is it suppose to work?

**Comment by julien-truffaut** [comment]
What do you by it doesn't work? It doesn't compile or he doesn't do what you expect? What error do you get? Which version of the library and scala are you using?

**Comment by user753** [comment]
I use scala 3.2.0 and monocle 3.2.0.
Code is working, but Idea's autocomplete doesn't work
![image](https://github.com/optics-dev/Monocle/assets/35331542/7ea5f3ce-c1c1-449b-93a4-3a0d1cbd2f16)
![image](https://github.com/optics-dev/Monocle/assets/35331542/d5885d8c-4b92-4928-9948-fc666d3cebc0)

**Comment by julien-truffaut** [comment]
Sorry I missed that it was about the auto complete in intellij. I am pretty sure it is because intellij doesn't support scala 3 well. Nothing we can do about it.

**Comment by user753** [comment]
Thanks. Does it work with metals?

**Comment by ghostdogpr** [comment]
I opened https://youtrack.jetbrains.com/issue/SCL-23387/Monocles-focus-macro-is-not-supported-in-Scala-3-works-with-Scala-2 because it's still not working.
