### ISSUE TITLE
release with scala-native 0.5

### ISSUE THREAD

**Issue by hamnis** [optics-dev/Monocle#1454]
The circe project would love if this can be released with scala-native 0.5 support

**Comment by julien-truffaut** [comment]
I will try to do it this week.

**Comment by julien-truffaut** [comment]
The publication failed:
```
2024-07-30 06:52:38.957Z error [Sonatype] 
java.io.IOException: Failure:java.util.concurrent.ExecutionException: java.io.IOException: Unexpected server response: 401 Content access is protected by token
```

**Comment by hamnis** [comment]
the publication now requires you to use sonatype tokens,
https://help.sonatype.com/en/user-tokens.html

**Comment by julien-truffaut** [comment]
> the publication now requires you to use sonatype tokens, https://help.sonatype.com/en/user-tokens.html

Thanks for the link. I found my sontaype user token. Do you know where should I put it so that it is picked up by the release process?

**Comment by hamnis** [comment]
assuming you are using sbt-typelevel or something similar you can just replace the secrets already used.
i think

SONATYPE_USERNAME
SONATYPE_PASSWORD 

are the secrets used.

**Comment by julien-truffaut** [comment]
Thanks, I updated the secrets but the publication failed again:
```
2024-07-30 08:40:02.026Z error [Sonatype] 
wvlet.airframe.http.HttpClientException: [401: Unauthorized]
	at wvlet.airframe.http.HttpClientException$.requestFailure(HttpClientException.scala:72)
```

**Comment by hamnis** [comment]
did you update both secrets?
![image](https://github.com/user-attachments/assets/da188e15-948c-410b-8405-2d5c87b986e8)
they should look something like this.

**Comment by hamnis** [comment]
make sure you update in the correct place, so if you have org secrets, and repository secrets, i think the repo secrets overrides the org secrets

**Comment by julien-truffaut** [comment]
> did you update both secrets? ![image](https://private-user-images.githubusercontent.com/75431/353390249-da188e15-948c-410b-8405-2d5c87b986e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMzAxNTQsIm5iZiI6MTcyMjMyOTg1NCwicGF0aCI6Ii83NTQzMS8zNTMzOTAyNDktZGExODhlMTUtOTQ4Yy00MTBiLTg0MDUtMmQ1Yzg3Yjk4NmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA4NTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNTIwZTNmYWJlNmY3MjQzZGFlZDVhMjhjNmNiNGQxM2VkYjYxOGNhMjU1NGM4NWI3NDZjYTk0MmRhMjE2MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gDHe79uWoBwyblo0KOg6M1g1bLlH_bVA6MwOKq6CvS8) they should look something like this.

I updated SONATYPE_USERNAME and SONATYPE_PASSWORD. I did it a second time, just to be sure.

**Comment by hamnis** [comment]
Then I have no idea whats wrong :(

Does the user you generated the tokens from have access to the `dev.optics` sonatype namespace?
You can see that in the download stats.

Do you publish to s01 or the legacy host?

**Comment by hamnis** [comment]
There seems to be some discussion on the typelevel discord in the `#general-dev` channel about this.

**Comment by julien-truffaut** [comment]
Thanks, I have requested to migrate to Central Portal from Legacy OSSRH. I should be able to add dev.optics namespace afterward.

**Comment by julien-truffaut** [comment]
It is published!

**Comment by hamnis** [comment]
@julien-truffaut Awesome! thanks a lot!
