### ISSUE TITLE
MakeClassy* macros

### ISSUE THREAD

**Issue by adelbertc** [optics-dev/Monocle#221]
In `Control.Lens` there is https://hackage.haskell.org/package/lens-4.11/docs/Control-Lens-TH.html which has `makeClassy` and `makeClassyPrisms` which create type classes for lenses/prisms for product/sum types.

An example of what `makeClassy` would generate would look something like [this](https://github.com/adelbertc/classyapp/blob/bda6431016954727543ce7d1b55d2d9c36cca508/src/main/scala/classyapp/DbConfig.scala)

An example of what `makeClassyPrisms` would generate would look something like [this](https://github.com/adelbertc/classyapp/blob/bda6431016954727543ce7d1b55d2d9c36cca508/src/main/scala/classyapp/DbError.scala)

I only just recently learned about this in [this talk](https://www.youtube.com/watch?v=GZPup5Iuaqw), but it seems to come in useful when your application have some independent effects (e.g. load from DB, send over network), and you want to compose each independent effect into a larger application-wide effect using something like [mtl](https://hackage.haskell.org/package/mtl)-y type classes, e.g. [AppConfig](https://github.com/adelbertc/classyapp/blob/bda6431016954727543ce7d1b55d2d9c36cca508/src/main/scala/classyapp/AppConfig.scala) and [AppError](https://github.com/adelbertc/classyapp/blob/bda6431016954727543ce7d1b55d2d9c36cca508/src/main/scala/classyapp/AppError.scala) to use in the top-level [application](https://github.com/adelbertc/classyapp/blob/bda6431016954727543ce7d1b55d2d9c36cca508/src/main/scala/classyapp/App.scala)

**Comment by julien-truffaut** [comment]
We will review macros for Scala 3
