### ISSUE TITLE
add intellij support for GenIso.fields

### ISSUE THREAD

**Issue by julien-truffaut** [optics-dev/Monocle#298]
see https://github.com/julien-truffaut/Monocle/issues/295

**Comment by japgolly** [comment]
FYI: this is where the magic happens:
https://github.com/JetBrains/intellij-scala/blob/idea15.x/src/org/jetbrains/plugins/scala/lang/psi/impl/toplevel/typedef/MonocleInjector.scala

There's a test too:
https://github.com/JetBrains/intellij-scala/blob/idea15.x/test/org/jetbrains/plugins/scala/lang/macros/MonocleLensesTest.scala

**Comment by julien-truffaut** [comment]
Thanks for the links

**Comment by japgolly** [comment]
I don't know how to do what we need here.
Asking for help: https://devnet.jetbrains.com/thread/475750

**Comment by julien-truffaut** [comment]
Will review macro for Scala 3
