### ISSUE TITLE
Auto publish website

### ISSUE THREAD

**Issue by julien-truffaut** [optics-dev/Monocle#372]
We should publish the website on each commit to master

**Comment by julien-truffaut** [comment]
I think it may have stopped working since the scala.js build change /cc @japgolly

**Comment by japgolly** [comment]
How did that work before? I didn't see anything in the SBT changes, could it be Travis via 903135dddccbde435a4903320e44d8909c2a6f89?

**Comment by julien-truffaut** [comment]
@japgolly sorry I was wrong, I don't think we ever auto publish.

**Comment by julien-truffaut** [comment]
not completely fixed, publish task is called but it fails for the following reason:
https://travis-ci.org/julien-truffaut/Monocle/jobs/143852110
```
[error] Cloning into '.'...
[error] Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
[error] Permission denied (publickey).
[error] fatal: Could not read from remote repository.
[error] 
[error] Please make sure you have the correct access rights
[error] and the repository exists.
```

**Comment by julien-truffaut** [comment]
see https://47deg.github.io/sbt-microsites/docs/publish-with-travis.html

**Comment by harmeetsingh0013** [comment]
Hi @julien-truffaut ,

As per https://47deg.github.io/sbt-microsites/docs/publish-with-travis.html documentation, there are two ways to configuring Travis with microsites using `sbt-ghpages` and `GitHub4s`. So, which way you would prefer to configure monocle site for publishing?
