### ISSUE TITLE
Add manual for using @Lenses

### ISSUE THREAD

**Issue by bwiercinski** [optics-dev/Monocle#900]
Both here:
https://www.optics.dev/Monocle/docs/optics/lens

and here:
https://github.com/optics-dev/Monocle/blob/master/macro/src/main/scala/monocle/macros/Lenses.scala

there is no info that I should add:
`addCompilerPlugin("org.scalamacros" % "paradise" % "2.1.1" cross CrossVersion.full)` in 2.12
or
compiler flag in 2.13.

i was getting:
`value _fieldName is not a member of object MyCaseClass`

Google also wasn't helpful :( 

pls can you add it to documentation. Thanks

**Comment by julien-truffaut** [comment]
I believe this documentation is on the front page of Monocle website, but it could also be added to the `Lens` page. 
Please feel free to send a PR. 

Thank you.

<img width="1342" alt="Screenshot 2020-09-20 at 15 57 12" src="https://user-images.githubusercontent.com/1859417/93714349-fd62e780-fb59-11ea-9846-ec19d793ab24.png">

**Comment by bwiercinski** [comment]
@julien-truffaut  I've added https://github.com/optics-dev/Monocle/pull/903 can you check it out?
