### ISSUE TITLE
Port Focus macro from Monocly

### ISSUE THREAD

**Issue by julien-truffaut** [optics-dev/Monocle#954]
@yilinwei prototype a great macro in [Monocly](https://github.com/optics-dev/Monocly/blob/master/src/main/scala/optics/poly/GenLens.scala) that allows writing optics this way:

```scala
case class User(name: String, address: Address, paymentMethods: Map[String, DebitCard])
case class Address(streetNumber: Int, postCode: String)
case class DebitCard(cardNumber: String, expirationDate: YearMonth, securityCode: String)

Focus[User](_.address.streetNumber)
// res: Lens[User, Int]

Focus[User](_.paymentMethods.index("Personal").expirationDate)
// res: Optional[User, YearMonth]

Focus[User](_.paymentMethods.*.cardNumber)
// res: Traversal[User, String]
```

The goal of this ticket is to implement `Focus` in the current version of Monocle, but for Scala 3 only. I guess we can implement it in two places:
1. in `core` module using a directory for Scala 3 (we used to have something similar for scala 2.12/2.11 specific code)
1. in a new `macro3` module only for Scala 3

It doesn't really matter right now, so I suggest we do what is the simplest.

**Comment by asjad02** [comment]
picking this one
