### ISSUE TITLE
Add shortcut for index

### ISSUE THREAD

**Issue by julien-truffaut** [optics-dev/Monocle#955]
Add an extension method for all optics (`Lens`, `Iso`, ...) and apply optics (`ApplyLens`, `ApplyIso`) for `index` so that we can do:

```scala
optic.index(10)
```

instead of

```scala
optic composeOptional index(10)
```

This should be very similar to what we have done for `each`:
https://github.com/optics-dev/Monocle/blob/master/core/shared/src/main/scala/monocle/Lens.scala#L284
https://github.com/optics-dev/Monocle/pull/908/files (but we moved it to implicit class)

Please write tests to check type inference is working fine (see https://github.com/optics-dev/Monocle/blob/master/test/shared/src/test/scala/monocle/LensSpec.scala#L121-L129)

**Comment by asjad02** [comment]
started working on this

**Comment by julien-truffaut** [comment]
Thanks @asjad02, don't hesitate to ask if you have any questions. Here or on gitter.

**Comment by julien-truffaut** [comment]
@asjad02 It seems @sapizhak worked on this issue and #956 together. I hope you didn't invest too much time on it.
