### ISSUE TITLE
Add shortcut for at

### ISSUE THREAD

**Issue by julien-truffaut** [optics-dev/Monocle#956]
Add an extension method for all optics (`Lens`, `Iso`, ...) and apply optics (`ApplyLens`, `ApplyIso`) for `at` so that we can do:

```scala
optic.at(10)
```

instead of

```scala
optic composeLens at(10)
```

This should be very similar to what we have done for `each`:
https://github.com/optics-dev/Monocle/blob/master/core/shared/src/main/scala/monocle/Lens.scala#L284
https://github.com/optics-dev/Monocle/pull/908/files (but we moved it to implicit class)

Please write tests to check type inference is working fine (see https://github.com/optics-dev/Monocle/blob/master/test/shared/src/test/scala/monocle/LensSpec.scala#L121-L129)

**Comment by sapizhak** [comment]
i have started working on this one
