### ISSUE TITLE
Setup a way to measure macro performance

### ISSUE THREAD

**Issue by julien-truffaut** [optics-dev/Monocle#965]
@propensive created a library call (probably)[https://github.com/propensive/probably] that can measure how long it takes to generate macros.

It woould be useful to measure the performance of `GenLens` and compare it to the new `Focus` macro https://github.com/optics-dev/Monocle/issues/954.

See some discussion on Twitter: https://twitter.com/propensive/status/1329745251679035394

**Comment by propensive** [comment]
Encouraged by this, I've just published Probably 0.8.0 which has simple support for running compiletime tests. You'll need to add a dependency on `com.propensive:probably-cli:0.8.0` and then,
```
import probably._
```

Then, in your macro definition, wrap an expression you want to check with,
```
ctx.test("test name") {
  <expression>
}.check { _ => true }
```

Currently the predicate on the check is required. It operates on the expression, and just returns a boolean. If you're more interested in timings (or counts) than properties of the expression's result, then just return `true`.

That should be all that's necessary to have a compiletime report printed at the end of compilation.

**Comment by asjad02** [comment]
picking this up

**Comment by propensive** [comment]
Give me a shout if you need any help, @asjad02!

**Comment by asjad02** [comment]
@propensive 
couldn't get the tabular output:: `sbt compile`, is there any additional info needed in build.sbt ([PR](https://github.com/optics-dev/Monocle/pull/985))

**Comment by julien-truffaut** [comment]
done, code is in this branch: https://github.com/optics-dev/Monocle/tree/benchmark-macro

Thanks @asjad02  and @propensive
