### ISSUE TITLE
Deprecate rarelly used features

### ISSUE THREAD

**Issue by julien-truffaut** [optics-dev/Monocle#979]
Early on the Monocle development, we added as many optics and combinators as we could possibly implement. But, this code needs to be maintained, tested and docummented which is pain, especially if no one use it. I propose that we drastically reduce the amount of code within Monocle and focus our effort in producing good user eperience and documentation for that subset. Here are the tentative list of items I propose to deprecate:

- [x] `Field1`, `Field2`  which provide `first`, `second`, .... We can use `at(1)`, `at(2)` instead
- [x] `Curry` which provides `curry` and `uncurry`
- [x] `Empty` which provides `empty` and `_isEmpty`
- [x] `Cons`, `Cons1`, `Snoc`, `Snoc1` which provide `headOption`, `head`, `tail`, `tailOption`, `last`, `lastOption`. 
- [x] `Reverse` which provides `reverse`
- [x] `Possible` which provides `possible`, `some` and `withDefault` shoulld cover most cases
- [x] The whole `generic` module which provides optics for `HList`, `Tuples`, `Product`, `Coproduct`
- [x] The whole `unsafe` module, we should move the code within `core` with documentation
- [x] The whole `state` module. This can be a separate project (hosted in optics-dev or not).
- [x] Symbolic composition operators `^|->`, `^|-?`, `^|->>`

If you are a heavy user of one of this feature, please make your case here. We will try our best to accomodate everyone.

**Comment by cquiroz** [comment]
From these I have used I think `reverse`, `unsafe` and `state`, buti I agree that we could deprecate them
